# Generated by Django 6.0.6 on 2026-06-14 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_assurance', models.CharField(choices=[('VIE', 'Assurance vie'), ('DECES', 'Décès-invalidité')], max_length=10)),
                ('description', models.TextField()),
                ('duree_mois', models.IntegerField()),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Produit d'assurance",
                'verbose_name_plural': "Produits d'assurance",
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaire_nom', models.CharField(max_length=150)),
                ('beneficiaire_contact', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurance.insuranceproduct')),
            ],
            options={
                'verbose_name': "Police d'assurance",
                'verbose_name_plural': "Polices d'assurance",
                'ordering': ['-created_at'],
            },
        ),
    ]
