# Generated by Django 6.0.6 on 2026-06-14 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_mois', models.IntegerField()),
                ('taux_interet', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('status', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_ANALYSE', 'En analyse'), ('APPROUVEE', 'Approuvée'), ('DECAISSEE', 'Décaissée'), ('REFUSEE', 'Refusée'), ('SOLDEE', 'Soldée')], default='SOUMISE', max_length=20)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='credits/documents/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_decaissement', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_credits', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de crédit',
                'verbose_name_plural': 'Demandes de crédit',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('date_prevue', models.DateField()),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=20)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='credits.creditrequest')),
            ],
            options={
                'verbose_name': 'Échéance',
                'verbose_name_plural': 'Échéances',
                'ordering': ['credit', 'numero'],
            },
        ),
    ]
