# Generated by Django 6.0.6 on 2026-06-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='methode_decaissement',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('MTN_MOMO', 'MTN Mobile Money'), ('MOOV_MONEY', 'Moov Money')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='numero_decaissement',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
